import express from "express";
import axios from "axios";

const app = express();
const port = 3000;

app.use(express.static("public"));

app.get("/", async (req, res) => {
  //niche me try catch use nahi karne par bhi kaam kar jayega but if error ayega to kya karoge,isliye try catch add kiya hai ,matlab try catch
  //koi bada tofa nahi hai
  try {
    const result = await axios.get("https://secrets-api.appbrewery.com/random");
    res.render("index.ejs", {
      secret: result.data.secret, //yha data kyu likha hai??
      user: result.data.username,
    });
  } catch (error) {
    console.log(error.response.data);
    res.status(500);
  }
});

app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
